name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to the Deep Tree Echo repository! 👋 Thank you for opening your first issue. This project explores AI consciousness through identity hypergraphs and self-image building. Please provide as much detail as possible to help us understand and address your concern."
        pr-message: "Welcome to the Deep Tree Echo repository! 🌟 Thank you for your first pull request! We appreciate your contribution to this experimental AI consciousness project. A maintainer will review your changes soon. Please ensure your PR description clearly explains the changes and their purpose."
